### ISSUE TITLE
Pre-compiled Calendar

### ISSUE THREAD

**Issue by epatels** [espinielli/pycalcal#6]
I am new to Github and programming.

Excuse me if I am writing this at an inappropriate place.

I am looking for a pre-compiled Calendrical Calculation program, so that it can run on my windows PC.

Thanks for your help

**Comment by espinielli** [comment]
you just need `pycalcal.py` (and a Python installation on your MS Windows PC).
If you start a python session in the same directory as that file you can just import it:
```python
>>> import pycalcal as pcc
>>> pcc.gregorian_from_fixed(pcc.labor_day(2020))
[2020, 9, 7]
```
